### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model payment!'

### ISSUE THREAD

**Issue by Sfdanila** [yandex-money/yandex-money-cms-opencart2#117]
После установки и настройки Y.CMS от Яндекс.Кассы (2.0.1) на ocStore 2.3.0.2 при заказе товара на этапе Способ оплаты получаю ошибку:
```
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model payment!' 
in /var/www/vhosts/domain.tld/opencart/system/storage/modification/system/engine/loader.php:169 Stack trace: 
#0 [internal function]: Loader->{closure}(Array, Array) 
#1 /var/www/vhosts/domain.tld/opencart/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array) 
#2 /var/www/vhosts/domain.tld/opencart/catalog/controller/checkout/payment_method.php(53): Proxy->__call('getMethod', Array) 
#3 /var/www/vhosts/domain.tld/opencart/catalog/controller/checkout/payment_method.php(53): Proxy->getMethod(Array, 1) 
#4 [internal function]: ControllerCheckoutPaymentMethod->index() 
#5 /var/www/vhosts/domain.tld/opencart/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) 
#6 /var/www/vhosts/domain.tld/opencart/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) 
#7 [internal function]: ControllerStartupRouter->index() 
#8 /var/www/vh in /var/www/vhosts/domain.tld/opencart/system/storage/modification/system/engine/loader.php on line 169
```
Подскажите, пожалуйста, что может вызывать ошибку и как её исправить?

**Comment by Sfdanila** [comment]
Вопрос снят, оказалось сам баран, вероятно оставались хвосты при установке разных версий модуля, установил чистый ocStore 2.3.х, заново установил [чистый модуль](https://github.com/yandex-money/yandex-money-cms-opencart2/blob/oc23x/ycms.ocmod.zip) и все заработало. Сорри за беспокойство!
